//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lokad.Rules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lokad.Rules.RuleResources", typeof(RuleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte array should not be longer than {0} bytes..
        /// </summary>
        internal static string Buffer_cant_be_longer_than_X {
            get {
                return ResourceManager.GetString("Buffer_cant_be_longer_than_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte array should have valid hash..
        /// </summary>
        internal static string Buffer_must_have_valid_hash {
            get {
                return ResourceManager.GetString("Buffer_must_have_valid_hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection of type &apos;{0}&apos; should not be null..
        /// </summary>
        internal static string Collection_X_cant_be_null {
            get {
                return ResourceManager.GetString("Collection_X_cant_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be greater than &apos;{0}&apos;..
        /// </summary>
        internal static string Date_must_be_greater_than_X {
            get {
                return ResourceManager.GetString("Date_must_be_greater_than_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double should represent a valid value..
        /// </summary>
        internal static string Double_must_represent_valid_value {
            get {
                return ResourceManager.GetString("Double_must_represent_valid_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression should be true: {0}..
        /// </summary>
        internal static string Expression_X_must_be_true {
            get {
                return ResourceManager.GetString("Expression_X_must_be_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional &apos;{0}&apos; should not be empty..
        /// </summary>
        internal static string Maybe_X_cant_be_empty {
            get {
                return ResourceManager.GetString("Maybe_X_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object should be same as the provided reference..
        /// </summary>
        internal static string Object_must_be_same_as_reference {
            get {
                return ResourceManager.GetString("Object_must_be_same_as_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object of type &apos;{0}&apos; should not be null..
        /// </summary>
        internal static string Object_X_cant_be_null {
            get {
                return ResourceManager.GetString("Object_X_cant_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule messages:.
        /// </summary>
        internal static string RuleException_header {
            get {
                return ResourceManager.GetString("RuleException_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should not be empty..
        /// </summary>
        internal static string String_cant_be_empty {
            get {
                return ResourceManager.GetString("String_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should not be longer than {0} characters..
        /// </summary>
        internal static string String_cant_be_longer_than_X {
            get {
                return ResourceManager.GetString("String_cant_be_longer_than_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should not be shorter than {0} characters..
        /// </summary>
        internal static string String_cant_be_shorter_than_X {
            get {
                return ResourceManager.GetString("String_cant_be_shorter_than_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should not contain unicode control characters..
        /// </summary>
        internal static string String_cant_contain_unicode_control_characters {
            get {
                return ResourceManager.GetString("String_cant_contain_unicode_control_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should not have uppercase characters..
        /// </summary>
        internal static string String_cant_contain_uppercase {
            get {
                return ResourceManager.GetString("String_cant_contain_uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should not contain following characters: {0}..
        /// </summary>
        internal static string String_cant_contain_X_characters {
            get {
                return ResourceManager.GetString("String_cant_contain_X_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should not end with trailing white-space character..
        /// </summary>
        internal static string String_cant_end_with_whitespace {
            get {
                return ResourceManager.GetString("String_cant_end_with_whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should not start with white-space character..
        /// </summary>
        internal static string String_cant_start_with_whitespace {
            get {
                return ResourceManager.GetString("String_cant_start_with_whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should be a valid email address..
        /// </summary>
        internal static string String_must_be_valid_email {
            get {
                return ResourceManager.GetString("String_must_be_valid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should be a valid host name..
        /// </summary>
        internal static string String_must_be_valid_host {
            get {
                return ResourceManager.GetString("String_must_be_valid_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not be equal to &apos;{0}&apos;..
        /// </summary>
        internal static string Value_cant_be_equal_to_X {
            get {
                return ResourceManager.GetString("Value_cant_be_equal_to_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not be greater than &apos;{0}&apos;..
        /// </summary>
        internal static string Value_cant_be_greater_than_X {
            get {
                return ResourceManager.GetString("Value_cant_be_greater_than_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not be less than &apos;{0}&apos;..
        /// </summary>
        internal static string Value_cant_be_less_than_X {
            get {
                return ResourceManager.GetString("Value_cant_be_less_than_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be equal to &apos;{0}&apos;..
        /// </summary>
        internal static string Value_must_be_equal_to_X {
            get {
                return ResourceManager.GetString("Value_must_be_equal_to_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be greater than &apos;{0}&apos;..
        /// </summary>
        internal static string Value_must_be_greater_than_X {
            get {
                return ResourceManager.GetString("Value_must_be_greater_than_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be less than &apos;{0}&apos;..
        /// </summary>
        internal static string Value_must_be_less_than_X {
            get {
                return ResourceManager.GetString("Value_must_be_less_than_X", resourceCulture);
            }
        }
    }
}
